apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  labels:
    name: httpserver
    app: httpserver
spec:
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1 
      maxUnavailable: 1 
  replicas: 3
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      nodeSelector:
        app: cc_apiserver
      containers:
        - name: httpserver
          image: paul803/cncamp-module3
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 20
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: paul-config