apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paul-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: paul-service
            port:
              number: 3000